input_channels: 3
latent_dim: 256
hidden_dims:
- 64
- 128
- 256
- 512
image_size: 64
lr: 0.001
kl_annealing: false
kl_start: 0.0
kl_end: 1.0
kl_annealing_epochs: 2
kl_warmup_epochs: 2
weight_decay: 0
betas:
- 0.9
- 0.999
use_scheduler: false
scheduler_patience: 3
scheduler_factor: 0.5
min_lr: 1.0e-06
dataset_name: celeba
data_dir: ./data
batch_size: 128
num_workers: 8
