input_channels: 3
latent_dim: 256
hidden_dims:
- 64
- 128
- 256
image_size: 32
lr: 0.0005
loss_type: L1
use_resnet: true
perceptual_weight: 1.0
kl_annealing: true
kl_start: 0.01
kl_end: 0.5
kl_annealing_epochs: 15
kl_warmup_epochs: 5
weight_decay: 0
betas:
- 0.9
- 0.999
use_scheduler: false
scheduler_patience: 3
scheduler_factor: 0.5
min_lr: 1.0e-06
dataset_name: cifar10
data_dir: ./data
batch_size: 256
num_workers: 8
